name: Ejecutar Selenium Diario

on:
  schedule:
    - cron: '*/1 * * * *'  # 1:00 AM en Bogotá (UTC-5 → 6:00 AM UTC) # 1 AM en Colombia (Render usa UTC+0, así que 6 AM UTC = 1 AM Bogotá)

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script
        run: python Main.py
